color:
  brandColors:
    - '#0C0402'
    - '#AA5600'
    - '#7E3200'
    - '#586381'
    - '#9AB2B4'
  brandStrength: 0.090088
  lightness: 0.898053
  rhythmicContrast: 0.599429
  saturation: 0.993385
layout_spectrum: 0.506579
name: update
typography_spectrum: 0.014254
